update/workflow
mspnp/fabrikam-dronedelivery-workload pull request #33
Opened 2023-11-13 12:31 UTC by v-fearam

Adding gitignore
Moving to net6
Updating libraries

2023-12-26 18:34 UTC, ferantivero requested changes

2023-12-26 18:34 UTC, ferantivero commented on src/shipping/workflow/Fabrikam.Workflow.Service.Tests/Fabrikam.Workflow.Service.Tests.csproj
> +    <PackageReference Include="xunit" Version="2.6.2" />
there are newer version for xunit. You can consider not updating them as they are minor.

2023-12-26 18:34 UTC, ferantivero commented on src/shipping/workflow/Fabrikam.Workflow.Service/WorkflowService.cs
> +using System.Text.Json;
consider sort & order the usings

2023-12-26 18:34 UTC, ferantivero commented on src/shipping/workflow/Fabrikam.Workflow.Service/WorkflowService.cs
> -        private IQueueClient _receiveClient;
could you please detail a bit why we are changing this implementation?

2023-12-27 12:26 UTC, v-fearam commented on src/shipping/workflow/Fabrikam.Workflow.Service/WorkflowService.cs
> -        private IQueueClient _receiveClient;
[Microsoft.Azure.ServiceBus](https://www.nuget.org/packages/Microsoft.Azure.ServiceBus) is deprecated and it is suggested change to [Azure.Messaging.ServiceBus](https://www.nuget.org/packages/Azure.Messaging.ServiceBus/).
We implementing following the new library

2023-12-27 12:30 UTC, v-fearam commented on src/shipping/workflow/Fabrikam.Workflow.Service/WorkflowService.cs
> +using System.Text.Json;
done

2023-12-27 12:35 UTC, v-fearam commented on src/shipping/workflow/Fabrikam.Workflow.Service.Tests/Fabrikam.Workflow.Service.Tests.csproj
> +    <PackageReference Include="xunit" Version="2.6.2" />
done

2024-01-03 19:51 UTC, merged