Update Drone Scheduler
mspnp/fabrikam-dronedelivery-workload pull request #34
Opened 2023-11-14 15:01 UTC by v-fearam

Net6
Library versions
KeyVault deprecated library changed

2023-12-26 18:36 UTC, ferantivero requested changes

2023-12-26 18:36 UTC, ferantivero commented on src/shipping/dronescheduler/Dockerfile
> +ENTRYPOINT ["dotnet", "Fabrikam.DroneDelivery.DroneSchedulerService.dll"]
Note: we should investigate a bit more before changing this best practice for containers.

2023-12-26 18:36 UTC, ferantivero commented on src/shipping/dronescheduler/scripts/run.sh
> -#!/bin/bash
Please let's do not delete this for now.

2023-12-27 12:38 UTC, v-fearam commented on src/shipping/dronescheduler/Dockerfile
> +ENTRYPOINT ["dotnet", "Fabrikam.DroneDelivery.DroneSchedulerService.dll"]
It was not working and I couldn't make it work again. Looking forward to working together on it.

2024-01-03 19:31 UTC, ferantivero approved these changes
LGTM

2024-01-03 19:50 UTC, merged